import { Component, OnInit } from '@angular/core';
import {person} from './../model/person';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  people:person[]=[{"S_No":1,"first_name":"Benetta","last_name":"Tingle","email":"btingle0@slashdot.org","gender":"Genderqueer","Age":30,"Password":"OTbfJXb9IQ"},
  {"S_No":2,"first_name":"Derby","last_name":"Langlands","email":"dlanglands1@mashable.com","gender":"Genderfluid","Age":47,"Password":"Lq21UyZFb"},
  {"S_No":3,"first_name":"Wakefield","last_name":"Braybrooke","email":"wbraybrooke2@buzzfeed.com","gender":"Agender","Age":28,"Password":"kycaY5"},
  {"S_No":4,"first_name":"Olympe","last_name":"Fannon","email":"ofannon3@europa.eu","gender":"Polygender","Age":56,"Password":"BeJDWEcctl"},
  {"S_No":5,"first_name":"Brynna","last_name":"Blacksland","email":"bblacksland4@examiner.com","gender":"Non-binary","Age":31,"Password":"wrN9MXFE"},
  {"S_No":6,"first_name":"Lizzy","last_name":"Birtonshaw","email":"lbirtonshaw5@epa.gov","gender":"Bigender","Age":48,"Password":"cFuHN7"},
  {"S_No":7,"first_name":"Conroy","last_name":"Daulton","email":"cdaulton6@nbcnews.com","gender":"Male","Age":69,"Password":"04W3jGuxnK"},
  {"S_No":8,"first_name":"Filberte","last_name":"Newis","email":"fnewis7@youtube.com","gender":"Male","Age":59,"Password":"qOZrNl5"},
  {"S_No":9,"first_name":"Katharina","last_name":"Haburne","email":"khaburne8@cocolog-nifty.com","gender":"Non-binary","Age":66,"Password":"65cqk2PUAJi"},
  {"S_No":10,"first_name":"Cheston","last_name":"Imlen","email":"cimlen9@miitbeian.gov.cn","gender":"Genderfluid","Age":26,"Password":"IC94XaVkOhG"},
  {"S_No":11,"first_name":"Malanie","last_name":"Gothliff","email":"mgothliffa@sfgate.com","gender":"Agender","Age":33,"Password":"IuSZp80"},
  {"S_No":12,"first_name":"Freddi","last_name":"Hannant","email":"fhannantb@blogspot.com","gender":"Bigender","Age":55,"Password":"AIcfy05"},
  {"S_No":13,"first_name":"Jimmy","last_name":"Olenov","email":"jolenovc@usgs.gov","gender":"Genderfluid","Age":56,"Password":"IKHvK0"},
  {"S_No":14,"first_name":"Anton","last_name":"Mattsson","email":"amattssond@cdbaby.com","gender":"Non-binary","Age":66,"Password":"PDCk3pIz"},
  {"S_No":15,"first_name":"Roseann","last_name":"Zecchinii","email":"rzecchiniie@vk.com","gender":"Agender","Age":69,"Password":"SnGtCM"},
  {"S_No":16,"first_name":"Joeann","last_name":"Boles","email":"jbolesf@phpbb.com","gender":"Bigender","Age":24,"Password":"fro4dBLBULQ4"},
  {"S_No":17,"first_name":"Freda","last_name":"Baum","email":"fbaumg@google.it","gender":"Agender","Age":55,"Password":"dRQQH7u3QbHx"},
  {"S_No":18,"first_name":"Guillermo","last_name":"Rowdell","email":"growdellh@imgur.com","gender":"Agender","Age":25,"Password":"2qXNK0gH"},
  {"S_No":19,"first_name":"Georgiana","last_name":"Lewis","email":"glewisi@1und1.de","gender":"Female","Age":50,"Password":"jRHO8vjrl"},
  {"S_No":20,"first_name":"Hayley","last_name":"Mackie","email":"hmackiej@cdbaby.com","gender":"Genderfluid","Age":35,"Password":"N4xsZM"},
  {"S_No":21,"first_name":"Andrei","last_name":"Bassano","email":"abassanok@surveymonkey.com","gender":"Agender","Age":68,"Password":"dqDQCcGI682"},
  {"S_No":22,"first_name":"Urbain","last_name":"de Mendoza","email":"udemendozal@mediafire.com","gender":"Non-binary","Age":32,"Password":"zRsPtf5"},
  {"S_No":23,"first_name":"Lyn","last_name":"McMichael","email":"lmcmichaelm@mlb.com","gender":"Agender","Age":41,"Password":"wDuCezlUV"},
  {"S_No":24,"first_name":"Marinna","last_name":"Piggens","email":"mpiggensn@surveymonkey.com","gender":"Bigender","Age":28,"Password":"we5O4Ohn8Mbo"},
  {"S_No":25,"first_name":"Marie-jeanne","last_name":"Pennaman","email":"mpennamano@army.mil","gender":"Genderfluid","Age":21,"Password":"ERRnq0"},
  {"S_No":26,"first_name":"Hannis","last_name":"Daveley","email":"hdaveleyp@wikipedia.org","gender":"Non-binary","Age":33,"Password":"Yn48cW"},
  {"S_No":27,"first_name":"Joline","last_name":"Gilchrist","email":"jgilchristq@miitbeian.gov.cn","gender":"Bigender","Age":51,"Password":"sx7lKnwT48rd"},
  {"S_No":28,"first_name":"Rhodia","last_name":"Sibthorpe","email":"rsibthorper@cbc.ca","gender":"Female","Age":28,"Password":"urzuv6SUtBSy"},
  {"S_No":29,"first_name":"Estrellita","last_name":"Sedman","email":"esedmans@cpanel.net","gender":"Non-binary","Age":43,"Password":"oT5jwpXdkJ"},
  {"S_No":30,"first_name":"Julie","last_name":"Caldairou","email":"jcaldairout@creativecommons.org","gender":"Agender","Age":37,"Password":"QqqXIPbt"},
  {"S_No":31,"first_name":"Winnifred","last_name":"Ramsted","email":"wramstedu@nytimes.com","gender":"Male","Age":66,"Password":"Lwwwvt"},
  {"S_No":32,"first_name":"Sidney","last_name":"Hutfield","email":"shutfieldv@youtube.com","gender":"Genderfluid","Age":26,"Password":"CLsi3n"},
  {"S_No":33,"first_name":"Steffi","last_name":"Setch","email":"ssetchw@msu.edu","gender":"Agender","Age":32,"Password":"xeIpF7N2D"},
  {"S_No":34,"first_name":"Manda","last_name":"Fehners","email":"mfehnersx@dion.ne.jp","gender":"Male","Age":30,"Password":"IO8OTIHkSI"},
  {"S_No":35,"first_name":"Nadine","last_name":"Meineking","email":"nmeinekingy@squidoo.com","gender":"Male","Age":35,"Password":"FoYVbOY4V"},
  {"S_No":36,"first_name":"Judi","last_name":"Scutter","email":"jscutterz@newyorker.com","gender":"Polygender","Age":25,"Password":"tVaAGFy"},
  {"S_No":37,"first_name":"Dorice","last_name":"Dalglish","email":"ddalglish10@w3.org","gender":"Female","Age":61,"Password":"HzUjBz65iU"},
  {"S_No":38,"first_name":"Jessalyn","last_name":"Yurenev","email":"jyurenev11@themeforest.net","gender":"Female","Age":33,"Password":"RuZCX1on8tF3"},
  {"S_No":39,"first_name":"Flinn","last_name":"Hames","email":"fhames12@sina.com.cn","gender":"Agender","Age":27,"Password":"TN5zDsZPyBK"},
  {"S_No":40,"first_name":"Remy","last_name":"Baseke","email":"rbaseke13@csmonitor.com","gender":"Male","Age":54,"Password":"MBRpaY32S0"},
  {"S_No":41,"first_name":"Tammi","last_name":"Greet","email":"tgreet14@a8.net","gender":"Agender","Age":30,"Password":"MGxR0Fmtly"},
  {"S_No":42,"first_name":"Yvette","last_name":"Attack","email":"yattack15@example.com","gender":"Genderfluid","Age":40,"Password":"R4rftMeO6"},
  {"S_No":43,"first_name":"Wesley","last_name":"Ousley","email":"wousley16@cornell.edu","gender":"Bigender","Age":44,"Password":"L6vO85sTwx"},
  {"S_No":44,"first_name":"Jana","last_name":"Swaden","email":"jswaden17@dagondesign.com","gender":"Genderfluid","Age":25,"Password":"4nbsSPc"},
  {"S_No":45,"first_name":"Tricia","last_name":"Sopper","email":"tsopper18@mediafire.com","gender":"Bigender","Age":42,"Password":"OttsAljDaF"},
  {"S_No":46,"first_name":"Tabb","last_name":"Aspinell","email":"taspinell19@lycos.com","gender":"Agender","Age":46,"Password":"k6uaAdFyQZ1"},
  {"S_No":47,"first_name":"Cherilynn","last_name":"Pavelka","email":"cpavelka1a@businessinsider.com","gender":"Male","Age":39,"Password":"PHgFFR4xv9d0"},
  {"S_No":48,"first_name":"Ingaberg","last_name":"Baptie","email":"ibaptie1b@amazon.co.jp","gender":"Genderqueer","Age":68,"Password":"o8IT7fbGx"},
  {"S_No":49,"first_name":"Cymbre","last_name":"Iacovone","email":"ciacovone1c@si.edu","gender":"Bigender","Age":69,"Password":"s9YOlDpo"},
  {"S_No":50,"first_name":"Meris","last_name":"McKellar","email":"mmckellar1d@cbc.ca","gender":"Male","Age":47,"Password":"ICYB9fuitnxQ"},
  {"S_No":51,"first_name":"Gaston","last_name":"Gremain","email":"ggremain1e@netscape.com","gender":"Genderfluid","Age":26,"Password":"ognIQDi"},
  {"S_No":52,"first_name":"Monro","last_name":"Passey","email":"mpassey1f@addtoany.com","gender":"Bigender","Age":47,"Password":"PdHnZyk"},
  {"S_No":53,"first_name":"Cheston","last_name":"Annion","email":"cannion1g@smh.com.au","gender":"Female","Age":22,"Password":"XGwUFXlxXB"},
  {"S_No":54,"first_name":"Marlin","last_name":"Spriggin","email":"mspriggin1h@wikia.com","gender":"Female","Age":21,"Password":"NRVQhBgybRpI"},
  {"S_No":55,"first_name":"Marve","last_name":"Jude","email":"mjude1i@topsy.com","gender":"Bigender","Age":26,"Password":"fXYDQU"},
  {"S_No":56,"first_name":"Lexy","last_name":"Lumley","email":"llumley1j@apache.org","gender":"Female","Age":32,"Password":"iFSfld5z2X"},
  {"S_No":57,"first_name":"Elsinore","last_name":"Girkins","email":"egirkins1k@deliciousdays.com","gender":"Genderfluid","Age":58,"Password":"TIaBqf8oMWG"},
  {"S_No":58,"first_name":"Dorothee","last_name":"Tyrer","email":"dtyrer1l@diigo.com","gender":"Genderfluid","Age":67,"Password":"jffxkiQXmucA"},
  {"S_No":59,"first_name":"Cyrillus","last_name":"Jobke","email":"cjobke1m@yahoo.co.jp","gender":"Bigender","Age":51,"Password":"SVVE2wZa"},
  {"S_No":60,"first_name":"Tomlin","last_name":"Roffe","email":"troffe1n@prlog.org","gender":"Genderfluid","Age":65,"Password":"5l4eVvC5ZtIe"},
  {"S_No":61,"first_name":"Fraze","last_name":"Borge","email":"fborge1o@theguardian.com","gender":"Genderqueer","Age":64,"Password":"fHfftwHyvy"},
  {"S_No":62,"first_name":"Matt","last_name":"Teggin","email":"mteggin1p@123-reg.co.uk","gender":"Male","Age":47,"Password":"ZiLoqBrP"},
  {"S_No":63,"first_name":"Torrance","last_name":"Mantrup","email":"tmantrup1q@dmoz.org","gender":"Genderqueer","Age":62,"Password":"TPrx570fuwd7"},
  {"S_No":64,"first_name":"Cale","last_name":"Ranken","email":"cranken1r@auda.org.au","gender":"Bigender","Age":55,"Password":"8ENy6t2W79TX"},
  {"S_No":65,"first_name":"Miner","last_name":"Shadfourth","email":"mshadfourth1s@ning.com","gender":"Female","Age":56,"Password":"vrCGQBif"},
  {"S_No":66,"first_name":"Amberly","last_name":"Hayworth","email":"ahayworth1t@bravesites.com","gender":"Agender","Age":49,"Password":"tae9BWVg"},
  {"S_No":67,"first_name":"Jaquenette","last_name":"Rosone","email":"jrosone1u@yahoo.co.jp","gender":"Genderfluid","Age":25,"Password":"0eayrfOiN"},
  {"S_No":68,"first_name":"Sherline","last_name":"Lochet","email":"slochet1v@reference.com","gender":"Female","Age":47,"Password":"dsRP78D"},
  {"S_No":69,"first_name":"Wat","last_name":"Risom","email":"wrisom1w@livejournal.com","gender":"Female","Age":56,"Password":"glyd8qmfeN"},
  {"S_No":70,"first_name":"Alysia","last_name":"Noli","email":"anoli1x@imageshack.us","gender":"Bigender","Age":48,"Password":"05NRRm"},
  {"S_No":71,"first_name":"Georgina","last_name":"Muress","email":"gmuress1y@admin.ch","gender":"Bigender","Age":35,"Password":"bH6QzW"},
  {"S_No":72,"first_name":"Christine","last_name":"Lintill","email":"clintill1z@digg.com","gender":"Polygender","Age":43,"Password":"qcG0r7Cv"},
  {"S_No":73,"first_name":"Jethro","last_name":"Gervaise","email":"jgervaise20@nationalgeographic.com","gender":"Bigender","Age":54,"Password":"kuK1muNhFn"},
  {"S_No":74,"first_name":"Annecorinne","last_name":"Fells","email":"afells21@mozilla.com","gender":"Non-binary","Age":57,"Password":"2cmcU13oV"},
  {"S_No":75,"first_name":"Walker","last_name":"Fernandes","email":"wfernandes22@addthis.com","gender":"Agender","Age":65,"Password":"NKUFelmLYo"},
  {"S_No":76,"first_name":"Amil","last_name":"Nellies","email":"anellies23@accuweather.com","gender":"Polygender","Age":65,"Password":"05cDH2AcadOh"},
  {"S_No":77,"first_name":"Nataniel","last_name":"Carrell","email":"ncarrell24@reverbnation.com","gender":"Bigender","Age":58,"Password":"hVnMJG"},
  {"S_No":78,"first_name":"Ossie","last_name":"Renny","email":"orenny25@cbsnews.com","gender":"Genderfluid","Age":27,"Password":"OOZgB9sVIhF"},
  {"S_No":79,"first_name":"Zoe","last_name":"Bleyman","email":"zbleyman26@sciencedaily.com","gender":"Non-binary","Age":47,"Password":"crOgBl"},
  {"S_No":80,"first_name":"Kennett","last_name":"Jenkin","email":"kjenkin27@alibaba.com","gender":"Male","Age":62,"Password":"W2CdQiJPac"},
  {"S_No":81,"first_name":"Piper","last_name":"Le Grand","email":"plegrand28@bandcamp.com","gender":"Genderqueer","Age":43,"Password":"RVSGwU"},
  {"S_No":82,"first_name":"Jemie","last_name":"Filler","email":"jfiller29@delicious.com","gender":"Genderqueer","Age":35,"Password":"wTaaMx2op2"},
  {"S_No":83,"first_name":"Vasilis","last_name":"Sowley","email":"vsowley2a@plala.or.jp","gender":"Agender","Age":49,"Password":"u65GXqkG7"},
  {"S_No":84,"first_name":"Roi","last_name":"Nutbrown","email":"rnutbrown2b@unicef.org","gender":"Genderqueer","Age":28,"Password":"1vRLnK6JfB"},
  {"S_No":85,"first_name":"Kasper","last_name":"Leach","email":"kleach2c@webmd.com","gender":"Agender","Age":63,"Password":"JJXu3Z73"},
  {"S_No":86,"first_name":"Phil","last_name":"Sevier","email":"psevier2d@dagondesign.com","gender":"Genderfluid","Age":46,"Password":"gR6RNvxnOH"},
  {"S_No":87,"first_name":"Shawnee","last_name":"Phillpot","email":"sphillpot2e@eepurl.com","gender":"Male","Age":41,"Password":"O1YN8xBfY"},
  {"S_No":88,"first_name":"Enos","last_name":"Ringwood","email":"eringwood2f@histats.com","gender":"Genderfluid","Age":20,"Password":"3q5pixHHi"},
  {"S_No":89,"first_name":"Fenelia","last_name":"Tilson","email":"ftilson2g@hostgator.com","gender":"Male","Age":62,"Password":"Cu7Qr97N"},
  {"S_No":90,"first_name":"Nicol","last_name":"Yoselevitch","email":"nyoselevitch2h@geocities.jp","gender":"Agender","Age":22,"Password":"XYP2DyJo"},
  {"S_No":91,"first_name":"Michelina","last_name":"Mahody","email":"mmahody2i@homestead.com","gender":"Genderqueer","Age":57,"Password":"LAXngyg"},
  {"S_No":92,"first_name":"Shawnee","last_name":"Tesyro","email":"stesyro2j@statcounter.com","gender":"Non-binary","Age":42,"Password":"Y2tN3Rj"},
  {"S_No":93,"first_name":"Connie","last_name":"Clare","email":"cclare2k@reverbnation.com","gender":"Polygender","Age":68,"Password":"2LUsJRXFV"},
  {"S_No":94,"first_name":"Angeline","last_name":"Mixworthy","email":"amixworthy2l@nature.com","gender":"Male","Age":58,"Password":"NEjs5Oys7F"},
  {"S_No":95,"first_name":"Silas","last_name":"Gosnoll","email":"sgosnoll2m@geocities.jp","gender":"Male","Age":53,"Password":"FTOCAL"},
  {"S_No":96,"first_name":"Flora","last_name":"Greeve","email":"fgreeve2n@gravatar.com","gender":"Agender","Age":37,"Password":"CoroSHsfaBJz"},
  {"S_No":97,"first_name":"Dagny","last_name":"Wildsmith","email":"dwildsmith2o@rakuten.co.jp","gender":"Male","Age":54,"Password":"tyS9owy"},
  {"S_No":98,"first_name":"Giuseppe","last_name":"Eves","email":"geves2p@cbslocal.com","gender":"Genderqueer","Age":61,"Password":"sUKkp4aaEoxU"},
  {"S_No":99,"first_name":"Jakie","last_name":"Pepall","email":"jpepall2q@creativecommons.org","gender":"Genderfluid","Age":56,"Password":"1nYrc2qNSU"},
  {"S_No":100,"first_name":"Urbain","last_name":"Stading","email":"ustading2r@imdb.com","gender":"Genderqueer","Age":62,"Password":"vdoxeHDRh"}];
  
  males:person[]=[];
  constructor() {
    this.males=this.people.filter(person=>person.Age<25);
   }
  ngOnInit(): void {
  }
}
